DISPLAY_MAP = {
    'athlete_id': 'Athlete ID',
    'name': 'Name',
    'region': 'Region',
    'team': 'Team',
    'affiliate': 'Affiliate',
    'gender': 'Gender',
    'age': 'Age',
    'height': 'Height',
    'weight': 'Weight',
    'fran': 'Fran',
    'helen': 'Helen',
    'grace': 'Grace',
    'filthy50': 'Filthy 50',
    'fgonebad': 'Fight Gone Bad',
    'run400': '400m Run',
    'run5k': '5K Run',
    'candj': 'Clean & Jerk',
    'snatch': 'Snatch',
    'deadlift': 'Deadlift',
    'backsq': 'Back Squat',
    'pullups': 'Pull-ups',
    'eat': 'Eating Habits',
    'train': 'Training Style',
    'background': 'Background',
    'experience': 'Experience',
    'schedule': 'Schedule',
    'howlong': 'Experience Duration'
}
